version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    app: 
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/app
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - redis
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_URL_CACHING: redis://redis:6379/0
        stdin_open: true
        tty: true

    redis:
        image: 'redis:5-alpine'
        command: redis-server
        ports:
        - '6379:6379'
        volumes:
        - 'redis:/data'

    sidekiq:
        depends_on:
        - 'db'
        - 'redis'
        build: .
        command: bundle exec sidekiq
        volumes:
        - '.:/project'
        - '/project/tmp' # don't mount tmp directory
        environment:
            REDIS_URL_SIDEKIQ: redis://host.docker.internal:6379/12
volumes:
    mysql-data:
    redis: